// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_configuration.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseConfiguration {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChFIF0mTVUS8YqT_22CQtQxN0sSu1rYyI',
    appId: '1:1009108172645:web:28555d52abf0fa9bb66b8c',
    messagingSenderId: '1009108172645',
    projectId: 'user-serch',
    authDomain: 'user-serch.firebaseapp.com',
    storageBucket: 'user-serch.firebasestorage.app',
    measurementId: 'G-17DFZSBN2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB6aWh2uE4k5md237CAPzX37M5H-EDAWg',
    appId: '1:1009108172645:android:2d249d3a6fb25708b66b8c',
    messagingSenderId: '1009108172645',
    projectId: 'user-serch',
    storageBucket: 'user-serch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAFKc0nlO-xX9uufML2oqSHP9r8AAIhOM',
    appId: '1:1009108172645:ios:f27b824b049cbb91b66b8c',
    messagingSenderId: '1009108172645',
    projectId: 'user-serch',
    storageBucket: 'user-serch.firebasestorage.app',
    iosBundleId: 'com.serchservice.user',
  );
}
