// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXEVNFK-llInR-yknHMvVuRFM_thHYrCc',
    appId: '1:825589816078:web:72b283dd61f9afe3bc955f',
    messagingSenderId: '825589816078',
    projectId: 'serch-service',
    authDomain: 'serch-service.firebaseapp.com',
    storageBucket: 'serch-service.appspot.com',
    measurementId: 'G-CXL7JSZRPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOhFkCTnEtO2ZOVasbeiTbLByQbgv5Omk',
    appId: '1:825589816078:android:eac9de002f6546e2bc955f',
    messagingSenderId: '825589816078',
    projectId: 'serch-service',
    storageBucket: 'serch-service.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtyJkqPDkl2FwJNuTwXFr1TUDwEo1-Ouk',
    appId: '1:825589816078:ios:65e73b58258302ebbc955f',
    messagingSenderId: '825589816078',
    projectId: 'serch-service',
    storageBucket: 'serch-service.appspot.com',
    iosBundleId: 'com.serch.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtyJkqPDkl2FwJNuTwXFr1TUDwEo1-Ouk',
    appId: '1:825589816078:ios:65e73b58258302ebbc955f',
    messagingSenderId: '825589816078',
    projectId: 'serch-service',
    storageBucket: 'serch-service.appspot.com',
    iosBundleId: 'com.serch.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXEVNFK-llInR-yknHMvVuRFM_thHYrCc',
    appId: '1:825589816078:web:318513b950fbbefdbc955f',
    messagingSenderId: '825589816078',
    projectId: 'serch-service',
    authDomain: 'serch-service.firebaseapp.com',
    storageBucket: 'serch-service.appspot.com',
    measurementId: 'G-Y3YD7863BH',
  );

}