// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_configuration.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseConfiguration {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBi3HUwayWOYzFimwm9HNDMsbHdfwsTOY',
    appId: '1:825589816078:web:4bd9dd84b9bd5c81bc955f',
    messagingSenderId: '825589816078',
    projectId: 'serch-service',
    authDomain: 'serch-service.firebaseapp.com',
    storageBucket: 'serch-service.firebasestorage.app',
    measurementId: 'G-F2WXVBD7EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOhFkCTnEtO2ZOVasbeiTbLByQbgv5Omk',
    appId: '1:825589816078:android:fe200945e3dd406fbc955f',
    messagingSenderId: '825589816078',
    projectId: 'serch-service',
    storageBucket: 'serch-service.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtyJkqPDkl2FwJNuTwXFr1TUDwEo1-Ouk',
    appId: '1:825589816078:ios:e70ebe5435b4dd85bc955f',
    messagingSenderId: '825589816078',
    projectId: 'serch-service',
    storageBucket: 'serch-service.firebasestorage.app',
    iosBundleId: 'com.serchservice.user',
  );
}
